src/Entity/Invoice.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InvoiceRepository")
 */
class Invoice
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $payment_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $paid;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPaymentDate(): ?\DateTimeInterface
    {
        return $this->payment_date;
    }

    public function setPaymentDate(\DateTimeInterface $payment_date): self
    {
        $this->payment_date = $payment_date;

        return $this;
    }

    public function getPaid(): ?bool
    {
        return $this->paid;
    }

    public function setPaid(bool $paid): self
    {
        $this->paid = $paid;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/InvoiceType.php
<?php

namespace App\Form;

use App\Entity\Invoice;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('payment_date')
            ->add('paid')
            ->add('user_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Invoice::class,
        ]);
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Form\InvoiceType;
use App\Repository\InvoiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/invoice")
 */
class InvoiceController extends AbstractController
{
    /**
     * @Route("/", name="invoice_index", methods={"GET"})
     */
    public function index(InvoiceRepository $invoiceRepository): Response
    {
        return $this->render('invoice/index.html.twig', [
            'invoices' => $invoiceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="invoice_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $invoice = new Invoice();
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($invoice);
            $entityManager->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/new.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_show", methods={"GET"})
     */
    public function show(Invoice $invoice): Response
    {
        return $this->render('invoice/show.html.twig', [
            'invoice' => $invoice,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="invoice_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Invoice $invoice): Response
    {
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/edit.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Invoice $invoice): Response
    {
        if ($this->isCsrfTokenValid('delete'.$invoice->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($invoice);
            $entityManager->flush();
        }

        return $this->redirectToRoute('invoice_index');
    }
}

templates/invoice/_delete_form.html.twig
<form method="post" action="{{ path('invoice_delete', {'id': invoice.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ invoice.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/invoice/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/invoice/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Invoice{% endblock %}

{% block body %}
    <h1>Edit Invoice</h1>

    {{ include('invoice/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('invoice_index') }}">back to list</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice index{% endblock %}

{% block body %}
    <h1>Invoice index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Payment_date</th>
                <th>Paid</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for invoice in invoices %}
            <tr>
                <td>{{ invoice.id }}</td>
                <td>{{ invoice.paymentDate ? invoice.paymentDate|date('Y-m-d') : '' }}</td>
                <td>{{ invoice.paid ? 'Yes' : 'No' }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('invoice_show', {'id': invoice.id}) }}">show</a>
                    <a class="btn btn-warning" href="{{ path('invoice_edit', {'id': invoice.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('invoice_new') }}">Create new</a>
{% endblock %}

templates/invoice/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Invoice{% endblock %}

{% block body %}
    <h1>Create new Invoice</h1>

    {{ include('invoice/_form.html.twig') }}

    <a href="{{ path('invoice_index') }}">back to list</a>
{% endblock %}

templates/invoice/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice{% endblock %}

{% block body %}
    <h1>Invoice</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ invoice.id }}</td>
            </tr>
            <tr>
                <th>Payment_date</th>
                <td>{{ invoice.paymentDate ? invoice.paymentDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Paid</th>
                <td>{{ invoice.paid ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('invoice_index') }}">back to list</a>

    <a class="btn btn-warning" href="{{ path('invoice_edit', {'id': invoice.id}) }}">edit</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}